
import json
import os
import datetime
import random
import string
from fastapi import FastAPI, UploadFile, File, HTTPException, Form, Body
from pydantic import BaseModel
from typing import List, Optional, Dict, Any
import uvicorn

app = FastAPI(title="AutoAuth Core Backend", version="3.4.1")

DB_PATH = "database.json"
AI_JSON_PATH = "ai.json"

# DATABASE INITIALIZATION
def init_db():
    if not os.path.exists(DB_PATH):
        initial_data = {
            "users": [],
            "applications": [],
            "api_keys": [],
            "licenses": [],
            "versions": [
                {"version": "3.4.1", "name": "Nebula-X", "released": "2024-02-25"}
            ],
            "logs": []
        }
        with open(DB_PATH, "w") as f:
            json.dump(initial_data, f, indent=2)

init_db()

def load_db():
    """Real-time database read."""
    with open(DB_PATH, "r") as f:
        return json.load(f)

def save_db(data):
    """Real-time database write."""
    with open(DB_PATH, "w") as f:
        json.dump(data, f, indent=2)

def load_ai_config():
    """Read global system config from ai.json."""
    if os.path.exists(AI_JSON_PATH):
        with open(AI_JSON_PATH, "r") as f:
            return json.load(f)
    return {}

# MODELS
class AppCreate(BaseModel):
    name: str
    version: str

class APIKeyCreate(BaseModel):
    name: str
    app_id: str
    permissions: List[str]
    version: str
    duration_value: int
    duration_unit: str

class LicenseCreate(BaseModel):
    name: str
    user: str
    duration_value: int
    duration_unit: str

class AuthValidation(BaseModel):
    api_key: str
    license_key: str
    version: Optional[str] = "3.4.1"

# ENDPOINTS
@app.get("/api/data")
async def get_all_data():
    return load_db()

@app.post("/api/application/create")
async def create_application(data: AppCreate):
    db = load_db()
    app_id = f"app_{''.join(random.choices(string.ascii_lowercase + string.digits, k=8))}"
    new_app = {
        "id": app_id,
        "name": data.name,
        "version": data.version,
        "created_at": datetime.datetime.now().isoformat()
    }
    db["applications"].append(new_app)
    save_db(db)
    return new_app

@app.post("/api/key/create")
async def create_api_key(data: APIKeyCreate):
    db = load_db()
    key_string = f"ak_live_{''.join(random.choices(string.ascii_lowercase + string.digits, k=24))}"
    
    expiry_date = datetime.datetime.now()
    if data.duration_unit == 'Days': expiry_date += datetime.timedelta(days=data.duration_value)
    elif data.duration_unit == 'Months': expiry_date += datetime.timedelta(days=data.duration_value * 30)
    elif data.duration_unit == 'Years': expiry_date += datetime.timedelta(days=data.duration_value * 365)
    
    app_ref = next((a for a in db["applications"] if a["id"] == data.app_id), {"name": "Unknown"})
    
    new_key = {
        "id": f"key_{''.join(random.choices(string.ascii_lowercase + string.digits, k=8))}",
        "name": data.name,
        "app_id": data.app_id,
        "app_name": app_ref["name"],
        "key": key_string,
        "permissions": data.permissions,
        "version": data.version,
        "created_at": datetime.datetime.now().isoformat().split('T')[0],
        "last_used": "Never",
        "status": "Active",
        "expiry": expiry_date.isoformat().split('T')[0]
    }
    db["api_keys"].append(new_key)
    save_db(db)
    return new_key

@app.delete("/api/key/{key_id}")
async def delete_api_key(key_id: str):
    db = load_db()
    db["api_keys"] = [k for k in db["api_keys"] if k["id"] != key_id]
    save_db(db)
    return {"status": "success"}

@app.post("/api/key/regenerate")
async def regenerate_api_key(key_id: str = Body(..., embed=True)):
    db = load_db()
    new_key_string = f"ak_live_{''.join(random.choices(string.ascii_lowercase + string.digits, k=24))}"
    for k in db["api_keys"]:
        if k["id"] == key_id:
            k["key"] = new_key_string
            save_db(db)
            return {"status": "success", "new_key": new_key_string}
    raise HTTPException(status_code=404, detail="Key not found")

@app.post("/api/ai/scan")
async def ai_scan_project(code: str = Form(...), file: Optional[UploadFile] = File(None)):
    config = load_ai_config()
    auth_url = config.get("auth", {}).get("auth_url") or "YOUR_AUTH_URL_HERE"
    api_key = config.get("credentials", {}).get("api_key") or "YOUR_API_KEY_HERE"
    version = config.get("version", {}).get("current_version") or "YOUR_VERSION_HERE"
    
    integrated_code = f"""// AUTO-GENERATED BY AUTOAUTH CORE AI SCANNER\nimport {{ AutoAuthClient }} from '@autoauth/core-sdk';\n\nconst auth = new AutoAuthClient({{\n  apiKey: "{api_key}",\n  authUrl: "{auth_url}",\n  version: "{version}"\n}});\n\nexport const initAuth = async () => {{\n  return await auth.initialize();\n}};"""
    return {"status": "success", "result": "Integration manifest synthesized.", "code": integrated_code}

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=8000)
